source 'https://rubygems.org'
gem 'github-pages'
gem 'html-proofer', '~> 3.0.0'
gem 'travis'
gem 'scss_lint'
gem 'json', github: 'flori/json', branch: 'v1.8'
gem 'mdl'
gem 'jekyll-picture-tag'
gem 'jemoji'
gem 'jekyll-paginate'
gem 'hologram'
